# Generated by Django 4.2.2 on 2024-06-28 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0004_remove_apppointment_course_remove_services_course_and_more"),
        ("users", "0005_alter_user_managers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="masseur",
            name="course",
        ),
        migrations.DeleteModel(
            name="Course",
        ),
    ]
