# Generated by Django 4.2.2 on 2024-06-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_masseur_course_delete_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="masseur",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Напишите что-нибудь",
                max_length=1000,
                null=True,
                verbose_name="О массажисте",
            ),
        ),
        migrations.AddField(
            model_name="masseur",
            name="phone",
            field=models.TextField(
                blank=True,
                help_text="Укажите телефон",
                max_length=35,
                null=True,
                verbose_name="Телефон",
            ),
        ),
        migrations.AlterField(
            model_name="masseur",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Укажите имя",
                max_length=35,
                null=True,
                verbose_name="Имя",
            ),
        ),
        migrations.AlterField(
            model_name="masseur",
            name="surname",
            field=models.CharField(
                blank=True,
                help_text="Укажите фамилию",
                max_length=75,
                null=True,
                verbose_name="Фамилия",
            ),
        ),
    ]
