# Generated by Django 4.2.2 on 2024-06-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_masseur_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="masseur",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите фото",
                null=True,
                upload_to="user/masseur/",
                verbose_name="Фото",
            ),
        ),
    ]
