# Generated by Django 4.2.2 on 2024-06-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="top_service",
            field=models.BooleanField(default=False, verbose_name="Топ услуга"),
        ),
    ]
