# Generated by Django 4.2.2 on 2024-06-28 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0007_alter_apppointment_course_alter_apppointment_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apppointment",
            name="email",
        ),
    ]
