# Generated by Django 4.2.2 on 2024-06-28 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("service", "0008_remove_apppointment_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="apppointment",
            name="email",
            field=models.ForeignKey(
                default=1,
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Почта",
            ),
        ),
    ]
