# Generated by Django 4.2.2 on 2024-06-28 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0011_alter_apppointment_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apppointment",
            name="email",
        ),
    ]
