# Generated by Django 4.2.2 on 2024-06-28 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apppointment",
            old_name="email",
            new_name="creator",
        ),
    ]
