# Generated by Django 4.2.2 on 2024-06-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0003_apppointment_service"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apppointment",
            name="course",
        ),
        migrations.RemoveField(
            model_name="services",
            name="course",
        ),
        migrations.AlterField(
            model_name="apppointment",
            name="date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата и время записи"
            ),
        ),
    ]
