# Generated by Django 4.2.2 on 2024-06-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0004_remove_apppointment_course_remove_services_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=10,
                null=True,
                verbose_name="Стоимость",
            ),
        ),
    ]
