# Generated by Django 4.2.2 on 2024-06-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0005_alter_services_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apppointment",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Имя"
            ),
        ),
        migrations.AlterField(
            model_name="apppointment",
            name="phone",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Телефон"
            ),
        ),
        migrations.AlterField(
            model_name="apppointment",
            name="surname",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Фамилия"
            ),
        ),
    ]
